name = "hution"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Simple and minimal personal blog theme inspired by Notion"
homepage = "https://github.com/jorgechato/hution.git"
tags = ["notion", "blog", "minimal", "simple"]
features = ["minimal", "simple", "responsive", "google analytics integration", "syntax highlight"]
min_version = "0.41.0"

[author]
  name = "Jorge Chato"
  homepage = "https://jorgechato.com"
